language: ruby
dist: bionic
rvm:
 - 2.6.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # JEKYLL_ENV=production

script:
 - bundle exec jekyll build

cache: bundler

deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET}
  skip_cleanup: true
  bucket: "sc-lib-ds-static"
  local_dir: _site
  upload_dir: dev/1847
  detect_encoding: true
  default_text_charset: "utf-8"
  on:
    branch: dev
branches:
    only:
        - dev


notifications:
  email:
    recipients:
      - digitalscholarship@swarthmore.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    secure: McLnT+wO18IeC7npVaqrUxxseKxIQIQECg255TlAxdXiAOKxLWX2sf4/dNPp/rB627cTvvE2WfAs5Mt1h0TPR7mnBGlgLromhtcjEOGDedyHM2mQYpjkwG/lkGhhifLCmcjwfuBQH2S2sbU0+o9TPr3/aFNK3TOIvKwefH9MztGuerla+yWpnH56Vw2Gu/RhSFWReLhoPVacVUvst43P4Ey5dmofq4KwbKfprw9rVV8oFjh7VMoZgmOc++mSXVaaj02/qOpO00jJXo8ZR44KKKzR3Ikjd1G2X7AgK7SYvPeVoy99yX0SC4FPeZBOK2fsonFWA3bJrDnZns9YBQwQ+65aiUGJen6/EZ62iZPWhPJVLJF37sKXSVrS0zJHSzYGwt3MH7vWUm77DDKfI6lzhDf/8mdpg82bOOMzuX1SUcf7HBgT6dRSns3ARW9Ko15rY4ZlAKAW4EjRgDHHl5UuUES5Krg8GfMZNPHNNnZ2SC3mwOmbcX4VQ2av7hoSTV/AuVmGQ5aCATWr1KUPYGfTK+C2w2U7Zh2lYbfbitKuSX37v//smWRWwCYrcPQcYRWgeHuwNVUKJqJwcXLCKWzZflm/0paQmnkn+vWjNSDfFLJ5lMcCyXh/z+GgaBc9C/U34fcamOlCr8JV3naxCDV99mavt5FNV3h0Pcl8mR422wA=