language: ruby
dist: bionic
rvm:
 - 2.6.5

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # JEKYLL_ENV=production

script:
 - bundle exec jekyll build

cache: bundler

deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET}
  skip_cleanup: true
  bucket: "sc-lib-ds-static"
  local_dir: _site
  upload_dir: dev/1847
  detect_encoding: true
  default_text_charset: "utf-8"
  on:
    branch: dev
branches:
    only:
        - dev


notifications:
  email:
    recipients:
      - digitalscholarship@swarthmore.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    secure: Ohp6mioD1KGFUxbvXXYPwrqFKWraX8Kk0vVh5tQrG0WswsbUxg8oOS5FNTqcUqLpC7CW8ivAUPjy2roeTLbZTOU7SRlGBLChMoCdcWI8mOT9vhyDoPTnqnxMp1vzHbHPLlfdXs7++wXfneYiarc1lNEzsen1q4HojJgMasnyJK/9AtTJ5hn1iOH8+BAUPFr74t158KbWeyUW9RhwZ3gPspVt1IlwdInqPWas9Jwp+M+qqDYujltMRDxonz7hRdpB+ANIHtOMnSSvSmiFqqin6oAKophxCXBsJWjHZGX9Rp6iSXYn7HWpZnLhl8H8J8I+1/DP1u0z7mqpK3Qh+OfHOuZslK6OPrSad1MiPG2pPauTQtuvHUROoyDhLw+y4xxGAqvbNVTGtdkqg5a8WQcjDDN0pKAYBibfQIkiurO9GbSelmOu3YOEQzUuwJlQ01qVmarDNn9fnuNHUT+8yWj8Lg2HuSxa6xE0bs9oWuFiQJrxryizw68XihL8jITfmPTMghfTjEoJLuJkuFuq74cW95a4ijRpqZ13ZOyh5zA/BQ9h2kbEBi08zncDDcH2p2XG3iokM8Eu4nHKSzqilWD2wl+KuZQMcCanoV5svvIr+wZQlgy/ig7TEoeiVsgot8JG+VEtgWtu798FxLQLF2I4YoCM5yPMdz2D4dh3kdHKF6k=
